config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :users do 
    member do 
      post :login
      post :reset
      post :registerEmail
      post :resetEmail
      post :setPassword
    end
  end

  resources :categories do 
    resources :products
    collection do
      post :getByCity
    end
  end

  resources :addresses do 
    collection do 
      get :suggestion
    end
  end

  resources :orders
  resources :products do
    member do
      post :getByCategory
    end
    collection do
      post :getByCityAndCategory
    end
  end

  get '/home/user', to: 'home#user', as: 'user_home'

  root to: 'categories#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :category
  belongs_to :user
  belongs_to :address
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new(category_id: params[:category])
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = current_user.orders.create(order_params)

    respond_to do |format|
      if @order.save
        OrderPaidanJob.perform_later(@order.id)
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:category_id, :address_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.slim
= simple_form_for(@order) do |f|
  = f.error_notification

  .form-inputs
    = f.association :category
    = f.association :address, collection: current_user.addresses
  .form-actions
    = f.button :submit

app/views/orders/edit.html.slim
h1 Editing order

== render 'form'

= link_to 'Show', @order
'|
= link_to 'Back', orders_path

app/views/orders/index.html.slim
.panel.panel-default
  .panel-heading
    | 订单
  .panel-body
    table.table.table-striped
      thead
        tr
          th Category
          th Address
          th Total price
          th Status
          th Courier status
          th Voucher status
          th Cleaning status
          th
          th

      tbody
        - @orders.each do |order|
          tr
            td = order.category.name
            td = order.address
            td = order.total_price
            td = order.status
            td = order.courier_status
            td = order.voucher_status
            td = order.cleaning_status
            td = link_to 'Show', order
            td = link_to 'Destroy', order, data: { confirm: 'Are you sure?' }, method: :delete

= will_paginate @orders, renderer: BootstrapPagination::Rails

app/views/orders/new.html.slim
h1 New order

== render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.slim
p
  strong Category:
  = @order.category.name
p
  strong Address:
  = @order.address.address
p
  strong Total price:
  = @order.total_price
p
  strong Status:
  = @order.status
p
  strong Courier status:
  = @order.courier_status
p
  strong Voucher status:
  = @order.voucher_status
p
  strong Cleaning status:
  = @order.cleaning_status

= link_to 'Back', orders_path