config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :users do 
    member do 
      post :login
      post :reset
      post :registerEmail
      post :resetEmail
      post :setPassword
    end
  end

  resources :categories do 
    resources :products
    collection do
      post :getByCity
    end
  end

  resources :addresses do 
    collection do 
      get :suggestion
    end
  end

  resources :orders
  resources :products do
    member do
      post :getByCategory
    end
    collection do
      post :getByCityAndCategory
    end
  end

  get '/home/user', to: 'home#user', as: 'user_home'

  root to: 'categories#index'
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = current_user.addresses.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to addresses_path, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to addresses_path, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def suggestion
    url = 'http://api.map.baidu.com/place/v2/suggestion'
    resp = RestClient.get url, {params: {region: '全国', output: 'json', ak: '9c0105d4f31da574429c49cca95c5566', query: params[:term]}}

    result = JSON.parse(resp)['result'].map do |result|
      {id: result['name'], text: result['name'], lat: result['location']['lat'], lng: result['location']['lng']}
    end
    
    render json: {results: result}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:address, :lat, :lng, :comment)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.slim
= simple_form_for(@address) do |f|
  = f.error_notification

  .form-inputs
    = f.input :address, as: :select
    = f.input :lat
    = f.input :lng
    = f.input :comment

  .form-actions
    = f.button :submit

javascript:
  $(function(){
    $("#address_address").select2({
      placeholder: "输入一个地址",
      theme: 'bootstrap',
      ajax: {
        url: '/addresses/suggestion.json',
        dataType: 'json',
        delay: 250,
        cache: false
      },
      minimumInputLength: 1
    })

    $("#address_address").on("change", function (e) {
      var data = $("#address_address").select2('data')[0];
      if(data){
        $("#address_lat").val(data['lat'])
        $("#address_lng").val(data['lng'])
      }
    });
  })

app/views/addresses/edit.html.slim
h1 Editing address

== render 'form'

= link_to 'Show', @address
'|
= link_to 'Back', addresses_path

app/views/addresses/index.html.slim
h1 Listing addresses

table.table.table-stripted
  thead
    tr
      th Address
      th Lat
      th Lng
      th Comment
      th
      th
      th

  tbody
    - @addresses.each do |address|
      tr
        td = address.address
        td = address.lat
        td = address.lng
        td = address.comment
        td = link_to 'Show', address
        td = link_to 'Edit', edit_address_path(address)
        td = link_to 'Destroy', address, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Address', new_address_path

app/views/addresses/new.html.slim
h1 New address

== render 'form'

= link_to 'Back', addresses_path

app/views/addresses/show.html.slim
p#notice = notice

p
  strong Address:
  = @address.address
p
  strong Lat:
  = @address.lat
p
  strong Lng:
  = @address.lng
p
  strong User:
  = @address.user

= link_to 'Edit', edit_address_path(@address)
'|
= link_to 'Back', addresses_path