config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :users do 
    member do 
      post :login
      post :reset
      post :registerEmail
      post :resetEmail
      post :setPassword
    end
  end

  resources :categories do 
    resources :products
    collection do
      post :getByCity
    end
  end

  resources :addresses do 
    collection do 
      get :suggestion
    end
  end

  resources :orders
  resources :products do
    member do
      post :getByCategory
    end
    collection do
      post :getByCityAndCategory
    end
  end

  get '/home/user', to: 'home#user', as: 'user_home'

  root to: 'categories#index'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = @category.products.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def getByCity
    @category = Category.where(["id in (SELECT categories_cities.category_id from categories_cities
WHERE categories_cities.city_id = ?)", params[:cityId]])
    respond_to do |format|
      if @category.empty?
        format.json { render :json => {:data => "Query failed"}.to_json }
      else
        format.json { render :json => {:data => @category}.to_json }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.fetch(:category, {})
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_block.html.slim
.text-center
  = link_to image_tag("#{qiniu_url(category.logo)}", size: '150x150'), category_path(category)
  br
  = category.name

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
- @categories.each_slice(2).each do |categories|
  .row 
    - categories.each do |category|
      .col-xs-6
        = render partial: 'categories/category_block', locals: {category: category}
  br

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
- @products.each_slice(2).each do |products|
  .row 
    - products.each do |product|
      .col-xs-6
        = render partial: 'products/product', locals: {product: product}
  br

= will_paginate @products, renderer: BootstrapPagination::Rails

= link_to '下单', new_order_path(category: @category), class: 'btn btn-info btn-sm'